In [29]:
import sklearn.preprocessing as prep
import numpy as np
from sklearn.linear_model import LinearRegression
import requests

X=np.random.choice(['female', 'male', 'high school', 'manager'], size=(1000,3))
Y=np.random.normal(10000, 20000, size=(1000,3))
ohe=prep.OneHotEncoder()
X1=ohe.fit_transform(X).toarray()
model=LinearRegression()
model.fit(X1,Y)
print(model.coef_)

js=requests.get('https://api.hh.ru/vacancies?text=Разработчик&per_page=100&only_with_salary=True').json()['items']
salary=np.array(list(map(lambda x: x['salary']['from'] if x['salary']['from'] is not None else x['salary']['to'],js)))
print(js[salary.argmax()]['id'],js[salary.argmax()]['name'],js[salary.argmax()]['salary'])

X=np.array(list(map(lambda x: list(np.array([x['salary']['from'],x['salary']['to'],x['id']],dtype=float)),js)))
X[1:10,0]

schedule=np.array(list(map(lambda x: x['schedule']['name'],js)))
lab=prep.LabelEncoder()

[[-3.09512991e+17 -3.09512991e+17 -3.09512991e+17 -3.09512991e+17
  -2.11350147e+18 -2.11350147e+18 -2.11350147e+18 -2.11350147e+18
   7.70426920e+17  7.70426920e+17  7.70426920e+17  7.70426920e+17]
 [-6.63122433e+17 -6.63122433e+17 -6.63122433e+17 -6.63122433e+17
  -9.20254259e+15 -9.20254259e+15 -9.20254259e+15 -9.20254259e+15
   1.85232098e+18  1.85232098e+18  1.85232098e+18  1.85232098e+18]
 [-3.53257915e+17 -3.53257915e+17 -3.53257915e+17 -3.53257915e+17
  -1.29826776e+18 -1.29826776e+18 -1.29826776e+18 -1.29826776e+18
  -1.25782692e+18 -1.25782692e+18 -1.25782692e+18 -1.25782692e+18]]
71136545 Разработчик С++ middle+ {'from': 1500000, 'to': 2200000, 'currency': 'KZT', 'gross': False}


In [30]:
lab.fit_transform(schedule.reshape(-1,1))

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([3, 3, 1, 3, 1, 1, 1, 3, 1, 1, 3, 1, 0, 0, 1, 3, 3, 1, 3, 3, 1, 3,
       1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 0, 1, 1, 1,
       3, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 3, 0, 1, 0, 2, 1, 1, 3, 1, 3, 1,
       3, 3, 1, 1, 1, 1, 1, 1, 0, 1, 3, 3, 1, 3, 0, 1, 3, 1, 1, 3, 3, 1,
       1, 1, 3, 0, 3, 3, 3, 1, 1, 1, 0, 1])

In [31]:
salaryfrom=np.array(list(map(lambda x: x['salary']['from'] if x['salary']['from'] is not None else None,js)))
mn=np.mean(list(filter(lambda x:x>1,np.where(salaryfrom.astype(str)=='None',1,salaryfrom))))

In [32]:
np.where(salaryfrom.astype(str)=='None',mn,salaryfrom.astype(float))

array([2.50000000e+04, 6.00000000e+03, 4.00000000e+05, 1.42259783e+05,
       4.00000000e+05, 1.50000000e+03, 3.20000000e+05, 5.00000000e+03,
       1.50000000e+04, 7.00000000e+04, 7.00000000e+03, 1.50000000e+04,
       1.00000000e+03, 2.50000000e+05, 5.00000000e+05, 5.00000000e+03,
       4.00000000e+03, 6.00000000e+04, 1.00000000e+05, 1.42259783e+05,
       5.00000000e+04, 2.50000000e+04, 6.00000000e+04, 4.00000000e+04,
       1.80000000e+05, 1.80000000e+05, 8.00000000e+04, 3.50000000e+04,
       1.80000000e+05, 9.00000000e+04, 8.00000000e+04, 6.00000000e+03,
       2.50000000e+05, 5.00000000e+04, 3.00000000e+05, 8.00000000e+04,
       1.42259783e+05, 3.00000000e+05, 1.20000000e+05, 6.00000000e+04,
       5.00000000e+04, 5.00000000e+04, 5.00000000e+04, 5.00000000e+04,
       7.00000000e+04, 5.00000000e+05, 5.00000000e+05, 1.50000000e+04,
       5.00000000e+04, 7.00000000e+04, 2.30000000e+05, 8.00000000e+04,
       1.42259783e+05, 2.50000000e+05, 2.50000000e+05, 5.00000000e+04,
      

In [5]:
np.corrcoef(np.where(salaryfrom.astype(str)=='None',mn,salaryfrom.astype(float)),shed)

NameError: ignored

In [6]:
minmax=prep.MinMaxScaler()
np.corrcoef(minmax.fit_transform((np.where(salaryfrom.astype(str)=='None',mn,salaryfrom.astype(float))).reshape(-1, 1)).flatten(), shed)

NameError: ignored

In [33]:
ohe.fit_transform(schedule.reshape(-1, 1)).toarray()

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [34]:
from sklearn.linear_model import LinearRegression


ohe=prep.OneHotEncoder()
X1=ohe.fit_transform(schedule.reshape(-1, 1)).toarray()
reg=LinearRegression()
reg.fit(X1,np.where(salaryfrom.astype(str)=='None',mn,salaryfrom.astype(float)))
reg.coef_

array([ 11474.63615974,  31824.85729917, -77751.34210113,  34451.84864221])

In [35]:
lst=list(map(lambda x: x[0]+'|'+x[1], zip(list(map(lambda x: 'низкая зп' if x<50000 else 'высокая зп',np.where(salaryfrom.astype(str)=='None',mn,salaryfrom.astype(float)))),
schedule)))
lst

['низкая зп|Удаленная работа',
 'низкая зп|Удаленная работа',
 'высокая зп|Полный день',
 'высокая зп|Удаленная работа',
 'высокая зп|Полный день',
 'низкая зп|Полный день',
 'высокая зп|Полный день',
 'низкая зп|Удаленная работа',
 'низкая зп|Полный день',
 'высокая зп|Полный день',
 'низкая зп|Удаленная работа',
 'низкая зп|Полный день',
 'низкая зп|Гибкий график',
 'высокая зп|Гибкий график',
 'высокая зп|Полный день',
 'низкая зп|Удаленная работа',
 'низкая зп|Удаленная работа',
 'высокая зп|Полный день',
 'высокая зп|Удаленная работа',
 'высокая зп|Удаленная работа',
 'высокая зп|Полный день',
 'низкая зп|Удаленная работа',
 'высокая зп|Полный день',
 'низкая зп|Полный день',
 'высокая зп|Удаленная работа',
 'высокая зп|Полный день',
 'высокая зп|Удаленная работа',
 'низкая зп|Удаленная работа',
 'высокая зп|Полный день',
 'высокая зп|Полный день',
 'высокая зп|Полный день',
 'низкая зп|Полный день',
 'высокая зп|Полный день',
 'высокая зп|Полный день',
 'высокая зп|Полный день',


In [28]:
lab=prep.LabelEncoder()
lst1=lab.fit_transform(np.reshape(lst,(-1,1)))
lst1

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([6, 6, 1, 2, 1, 4, 1, 6, 4, 1, 6, 4, 3, 0, 1, 6, 6, 1, 2, 2, 1, 6,
       1, 4, 2, 1, 2, 6, 1, 1, 1, 4, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1,
       2, 1, 1, 4, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 3, 5, 4, 4, 2, 1, 2, 1,
       2, 2, 1, 1, 4, 4, 4, 1, 0, 1, 2, 2, 1, 2, 0, 1, 2, 1, 1, 2, 6, 4,
       1, 1, 2, 0, 2, 6, 6, 1, 1, 1, 3, 4])

In [37]:
from collections import Counter

X=np.reshape([x[1] for x in sorted(Counter(lst).items(),key=lambda x:x[0])],(1,7))
X

array([[ 7, 45, 20,  3, 13,  1, 11]])